### ISSUE TITLE
Getting an UnsatisfiedLinkError relating to this library

### ISSUE THREAD

**Issue by gwynjudd** [sqlc/SQLiteConnector#2]
Hello,

I don't really have much to go on here, but I am getting a few reports of this from the play store. Any suggestions as to what might be going wrong or how to proceed would be much appreciated.

```
Type

java.lang.UnsatisfiedLinkError

Exception java.lang.UnsatisfiedLinkError:
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1082)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1003)
  at java.lang.System.loadLibrary (System.java:1661)
  at io.liteglue.SQLiteConnector.<init> (SQLiteConnector.java:8)
  at io.sqlc.SQLiteConnectorDatabase.<clinit> (SQLiteConnectorDatabase.java)
  at io.sqlc.SQLitePlugin.openDatabase (SQLitePlugin.java:212)
  at io.sqlc.SQLitePlugin.access$000 (SQLitePlugin.java:28)
  at io.sqlc.SQLitePlugin$DBRunner.run (SQLitePlugin.java:328)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)
```

**Comment by gosantoro** [comment]
Hi, I have the same problem, it occurs in some Xiaomi and Samsung devices (ie: Redmi Note 13 Pro 5G, Xiaomi 11 Lite 5G NE)

**_Crashlytics info:_**

```
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/~~491wea1LMSEp6xet51SJhA==/ar.com.osde.ads-xQlBACZeWoaRXk-V7qkcjw==/split_config.arm64_v8a.apk!/lib/arm64-v8a/libsqlc-ndk-native-driver.so" .dynamic section header was not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
       at java.lang.System.loadLibrary(System.java:1661)
       at io.liteglue.SQLiteConnector.<init>(:22)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at GoOdLeVeL.abas.abat(:54)
       at io.sqlc.SQLiteConnectorDatabase.<clinit>(:9)
       at io.sqlc.SQLitePlugin.openDatabase(:76)
       at io.sqlc.SQLitePlugin.-$$Nest$mopenDatabase(:9)
       at io.sqlc.SQLitePlugin$DBRunner.run(:23)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

Do you have any answer or update? 

Regards.
